### ISSUE TITLE
3분 미리보기 오류입니다.

### ISSUE THREAD

**Issue by taxdriver4u** [soju6jan/tving#3]
안드로이드tv 기반인 쉴드tv를 사용하고 있습니다.
티빙 유료 가입자 입니다. 
티빙 애드온(plugin.video.tving) 0.4.0을 다운받아서 kodi에 설치하였습니다.
라이브 채널 중 앞에 'ch'가 붙은 채널만 정상적으로 방송됩니다.
그외 나머지 라이브 채널, 다시보기 컨텐츠 전부 3분미리보기만 됩니다.

로그파일이 어디에 있는지를 몰라서 첨부를 못했습니다.

**Comment by taxdriver4u** [comment]
[login.zip](https://github.com/soju6jan/tving/files/2545075/login.zip)
로그파일이 먼지 몰라서 
login.data 파일 첨부하였습니다.

**Comment by soju6jan** [comment]
로그인 정상적으로 되었습니다. 이용권 확인해보세요.

**Comment by taxdriver4u** [comment]
무제한 플러스(뷰잉 6개월) 180일권 사용중입니다.
웹페이지로 접속하면 아무 문제없이 잘 됩니다.
아이디 비번 알려드리면 한번 확인해 주실수 있는지요.(이건 너무 번거롭게 해드리는거 같아서 그냥 부탁해봅니다.)

**Comment by soju6jan** [comment]
네.. 계정정보 보내주세요. cybersol@naver.com

**Comment by taxdriver4u** [comment]
보내드렸습니다.

**Comment by taxdriver4u** [comment]
티빙 비밀번호를 특수문자를 빼고 변경하려고 하였으나
영문, 숫자, 특수문자를 반드시 포함해서 8자 이상으로 하도록 되어 있습니다.
그래서 다른 특수문자로 바꾸어 보았지만 여전히 미리보기만 됩니다.  
바꾼 비번 다시 보내드렸습니다.

**Comment by soju6jan** [comment]
수정했습니다. 
이용권의 문제인지 알았는데, 인코딩 문제였네요.
엄청 큰 버그였고, 이제껏 미리보기만 된다고 하셨던 분들이 계실 때 단순히 사용자의 잘못이라고 생각하고 말았는데, 제 잘못이었네요. (제 계정의 토큰에는 문제가 발생하지 않아 확인을 못했습니다.)
아무튼 제공해주신 계정으로 큰 문제점을 수정했습니다. 
감사합니다.

**Comment by taxdriver4u** [comment]
이제 잘 되네요.
너무 감사드립니다.
푹, 옥수수, 티빙 너무 너무 잘 쓰겠습니다
