### ISSUE TITLE
끊김현상

### ISSUE THREAD

**Issue by taxdriver4u** [soju6jan/tving#4]
kodi용 티빙애드온을 잘 사용하는 사용자 입니다. 얼마전 로그인 이슈를 문의했던 사용자 이기도 하고요.

kodi에서 티빙 다시보기를 하다보면 영상이 끊김현상이 있습니다. 그러니까 재생은 계속 되는데 내용이 짧게 짧게 생략되어 재생되는 식입니다. 

해결하는 팁이 있을런지요

**Comment by soju6jan** [comment]
해상도를 낮추는 것 밖에 없습니다.
이건 티빙 사이트에서 플래쉬로 시청하는 것과 코디에서 시청하는 것은 아무 차이가 없습니다.
코디에서 시청해서 끊긴다면, 정식 사이트에서 시청해도 끊길 겁니다.
아마도 많이 끊기는 시간대가 있을겁니다.
새벽 5시에 시청해보세요.. 같은 콘텐츠도 버퍼링없이 재생될 겁니다.

**Comment by taxdriver4u** [comment]
넵 감사합니다. 
시놀리지 나스 713+를 사용하고 있습니다.
나스에 klive 서버를 올리고 싶은데, 지식이 마니 필요한 부분인지요.
