### ISSUE TITLE
KODI 16.1 사용자입니다.

### ISSUE THREAD

**Issue by tmdgns99** [soju6jan/tving#5]
딜라이브 OTT장비가 KODI 16.1 까지 지원하는 관계로 KODI 구버젼을 사용하고 있습니다.
tving을 실행시키면 로그인 정보를 입력했음에도 "저장된 로그인 정보가 없습니다. 지금 설정하시겠습니까?" 라고 나옵니다.
1. "예"를 누르면 저장된 로그인 정보가 나오더라구요.. => 여기서 로그인 정보를 확인하고 "확인"을 누르면 티빙이 종료됩니다.
2. "아니오"를 누르면 3분 미리보기로 실행됩니다.

혹시 확인 가능하시면 바쁘시겠지만 부탁드립니다.
덕분에 즐거운 시간 보내고 있습니다. 감사합니다.  ^^

**Comment by soju6jan** [comment]
이 플러그인은 되면 좋고 아니면 말고인 프로그램(?)입니다.
저보고 코디 16.1을 설치해서 확인 하라는 건가요? 제가 된다고 해도 저 장비가 없는데 어쩌라는 건가요?
다 떠나서 안되는 순간의 kodi.log 파일만 올려주세요.
파일위치는 검색하시구요
