### ISSUE TITLE
티빙 끊김 이슈

### ISSUE THREAD

**Issue by taxdriver4u** [soju6jan/tving#6]
일전에 문의드렸던 이슈입니다.

티빙 시청할시  라이브채널은 끊김없이 잘 재생됩니다. 그런데 지난방송 다시보기하는 경우 방송은 계속 재생이 되는데, 중간 중간 맥락없이 1~2초 장면이 뚝뚝 끊기면서 재생되는 문제가 발생합니다.

>티빙애드온으로 시청하면서 동시에 티빙 자체 어플로 지난방송 다시보기를 재생해보니, 티빙 자체 어플에서는 그런 현상이 나타나지 않았습니다.
>또 새벽 5에 재생해봤지만, 결과는 시간대와 관계없이 뚝뚝 1~2가 사라지는 끊김현상이 발생하였습니다.

일단 티빙은 klive_server에만 사용하고 지난방송 다시보기는 자체어플을 이용하고 있습니다.

앱개발에 참고하시라 알려드립니다.

배포해주신 앱들 너무너무 잘 쓰고 있고 감사드립니다.

**Comment by taxdriver4u** [comment]
코디가 문제였네요. 해결했습니다.  
감사합니다.

**Comment by pp080808** [comment]
taxdriver4u님
코디 어떻게 조정해서 해결하신거죠?
전 계속 발생해서리..
